# Generated by Django 3.0.8 on 2020-07-12 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_point', models.IntegerField(blank=True, null=True)),
                ('prize', models.IntegerField(blank=True, null=True)),
                ('game_state', models.CharField(choices=[('S', 'STARTED'), ('E', 'ENDED'), ('P', 'PAID')], max_length=1)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
