# Generated by Django 3.0.8 on 2020-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
